spring.application.name=photoProject
server.port=8085

# 1. Yerel PostgreSQL Veritabanı Bağlantısı (URL'nin sonundaki photo_db kısmını DBeaver'da verdiğin isimle aynı yapmalısın)
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/photo_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# 2. Hibernate Ayarları (Entity sınıflarını okuyup tabloları otomatik oluşturması için hayati önem taşır)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true

# 3. Görsel Yükleme Limitleri (İleride Cloudinary'ye yüksek çözünürlüklü fotoğraf atarken hata almamak için)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# JWT Configuration
jwt.secret-key=${JWT_SECRET}
jwt.expiration=1800000
jwt.refresh-expiration=604800000

#Cloudinary Settings
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
cloudinary.folder=photoProject

#Kafka
spring.kafka.bootstrap-servers=${KAFKA_HOST:localhost}:9092
spring.kafka.consumer.group-id=photoproject-notification-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.tarikturkdil.dto
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

#Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=6379
refresh-token.expiration-days=2
